# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
    - title: Exciting New Features 🎉
      labels:
        - enhancement
    - title: Bug fixes🧑‍🔧 🐞
      labels:
        - enhancement
    - title: Doc improvements 📚
      labels:
        - doc
        - documentation
    - title: Other Changes
      labels:
        - "*"

